### PR TITLE
beginnings of an nlang.nyc blogring

### PR DESCRIPTION
**Pull request by katychuang**

### CODE REVIEW

**Comment by katychuang** [comment]
screen shot 2017-04-14 at 5 17 42 pm

did some quick and dirty css work to prototype this blogring listing. will need to measure out more precisely the block sizes when I have more time to work it out.

**Comment by katychuang** [comment]
Made a couple more changes

**Comment by shonfeder** [comment]
Waiting on katychuang/nlangnyc.github.io#1 to be merged into this branch, then it looks all good to me!

**Comment by katychuang** [comment]
Merged! 👍 😄

**Comment by ghost** [comment]
👍 👍 👍

**Pull request merged**
